name: Release

on:
  push:
    branches:
      - 1.20.1
  workflow_dispatch:

jobs:
  release:
    uses: RadonCoding/origins-extra-keybinds-forge/.github/workflows/release-template.yml@main
    with:
      curse_game_versions: "Minecraft 1.20:1.20.1,Forge,NeoForge,environment:Client"
      modrinth_game_version: "1.20.1"
      loaders: |
        forge
        neoforge
    secrets: inherit