name: Synchronize

on:
  push:
    branches:
      - main
    paths:
      - README.md
      - LICENSE
      - .github/workflows/release.yml
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Syncronize to version branches
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          for branch in $(git branch -r | grep 'origin/1\.' | sed 's|origin/||'); do
            git checkout $branch
            git checkout main -- README.md LICENSE .github/workflows/release.yml
            git commit -m "Synchronization" || echo "Nothing to synchronize for $branch"
            git push origin $branch
          done
