name: Synchronize

on:
  push:
    branches:
      - main
    paths:
      - README.md
      - LICENSE

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Syncronize to version branches
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          for branch in 1.16.5 1.18.2 1.19.2 1.20.1; do
            git checkout $branch
            git checkout main -- README.md LICENSE
            git commit -m "Synchronize README.md and LICENSE from main" || echo "Nothing to sync for $branch"
            git push origin $branch
          done
